### ISSUE TITLE
Atmospheric turbulence simulation for dynamic scenes

### ISSUE THREAD

**Issue by Shengqi77** [Riponcs/QuickTurbSim#1]
Hello！ I would like to ask if this simulator is capable of accurately simulating atmospheric turbulence in dynamic scenes and whether it takes temporal correlation into account?

**Comment by Riponcs** [comment]
Yes, the simulator is capable of accurately simulating dynamic scenes while considering temporal correlation. In `RunQuickTurbSim.py`, under the `config `section, you can adjust the `temp_Scale `variable to control the level of temporal correlation between frames. Setting `temp_Scale = 1` or lower number will maintain a high level of correlation, while values of `temp_Scale = 10` or higher will result in lower temporal correlation.
